baseURL: https://nereidkwok.netlify.app/
languageCode: en-us
title: Nereid Kwok
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner: 
    buttonText: Get to know me
   # subtitle: |-
   #  A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
   # AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Nereid Kwok Portfolio
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom NW1 4SA
        street: Regent's Park
        title:  London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: nkwok.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 7782374750
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Nereid Kwok 2021
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: fa-twitter
      #  label: Twitter
       # url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/nedkwok/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/neddyk/
      - icon: fa-github
        label: GitHub
        url: https://github.com/nereidkwok/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/nereidkwok/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Learn More About Me
        url: blogs/bio
    button2:
      - name: My Resume
        url: /NereidKwok_CV.pdf
    links:
      - name: Home
        url: '#'
      - name: Projects
        url: blogs
     # - name: Generic Blog
      #  url: ipsum
      #- name: Elements
      #  url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: picbio.jpeg
        subtitle: Know more about me
        title: Nereid's Biography
        url: blogs/bio
      - image: picstock.jpg
        subtitle: Finance
        title: Returns of financial stocks
        url: blogs/stocks
      - image: picbike.jpg
        subtitle: Replication
        title: Excess rentals in TfL bike sharing
        url: blogs/bike
      - image: picsalary.jpg
        subtitle: Relationship
        title: Omega Group plc - Pay Discrimination
        url: blogs/omega
      - image: picyouth.jpg
        subtitle: Hypothesis testing
        title: Youth Risk Behavior Surveillance
        url: blogs/youth
      - image: picgdp.jpg
        subtitle: Trend comparison
        title: GDP Among Countries
        url: blogs/gdp
  two:
    buttonText: Take a look at my projects
    enable: yes
    subtitle: This portfolio aggregates my work over my Masters of Analytics and Management studies at London Business School. The website will be consistently updated with my upcoming projects. Please look forward to my future projects! If you would like to contact me, feel free to see me a message. 
    title: More about this project
    url: blogs
